### PR TITLE
add path to deletion cookie

### PR DESCRIPTION
**Pull request by SebRollen**
Hi again @LukeMathWalker,

In the same way as https://github.com/LukeMathWalker/actix-web-flash-messages/pull/2, I had some issues with cookies not being deleted when using `session.purge()`, and it looks like it has to do with the path of the deletion cookie not matching the path of the original session cookie. Let me know if you want me to add in a test!

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
I'd definitely like a test if you have the time to write one 😁

**Comment by SebRollen** [comment]
Added a test! While writing the test, I also noticed that the deletion cookie is not set to insecure even if the original session cookie was - this works fine in terms of actually deleting the cookie from what I can tell but thought I would point it out.

Another potential issue is that the domain does not seem to be set on the cookies even when specified in the middleware builder ([see here](https://github.com/LukeMathWalker/actix-extras/pull/1/commits/99f81e15bc3b8e92e1fcfeadb16b51bf4b2a8686#diff-88d482942cac4da45f031a52029fd5103c37f5a45e91a0a02bf63179fcaa66f6R25))

**Comment by LukeMathWalker** [comment]
The behaviour with `Secure` seems to match what browsers do, but it might be worth setting that property just to future-proof around changes there in the future.
The domain looks like a bug, yep.

**Comment by SebRollen** [comment]
Okay, I updated the domain behavior, and did some more digging on the secure attribute. From [IETF RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.3) (emphasis mine):

>    11.  If the cookie store contains a cookie with the same _**name,**_
>         _**domain, and path**_ as the newly created cookie:
> 
>         1.  Let old-cookie be the existing cookie with the same name,
>             domain, and path as the newly created cookie.  (Notice that
>             this algorithm maintains the invariant that there is at most
>             one such cookie.)
> 
>         2.  If the newly created cookie was received from a "non-HTTP"
>             API and the old-cookie's http-only-flag is set, abort these
>             steps and ignore the newly created cookie entirely.
> 
>         3.  Update the creation-time of the newly created cookie to
>             match the creation-time of the old-cookie.
> 
>         4.  Remove the old-cookie from the cookie store.

Since there is no mention of the `secure` attribute, but explicit mentions of `name`, `domain`, and `path`, I think the current behavior is correct, so no need to change things there.

**Comment by SebRollen** [comment]
One more update: since point ii of the spec above states that a removal cookie from a non-HTTP api will be ignored if the original cookie was set with http-only, _I think_ we also need to derive the http-only attribute from the original cookie. I implement that in https://github.com/LukeMathWalker/actix-extras/pull/1/commits/7fed8599a2747af3d2cfe7272d20d7e7da9e8be7

**Comment by LukeMathWalker** [comment]
Everything looks 👌🏻 - thanks for taking the time!

**Pull request merged**
